openapi: "3.0.0"
info:
  description: "This is RESTful API to serve images in different sizes"
  version: "1.0.0"
  title: "Imageserver"
  license:
    name: "MIT"

paths:
  /image:
    post:
      summary: "Upload new image to the server"
      operationId: "addImg"
      requestBody:
        content:
          image/png:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: UUID of uploaded image
  
  /image/{id}:
    delete:
      summary: "Delete image from server"
      operationId: "deleteImg"
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: "Image deleted"
          
    get:
      summary: "Get original image, converted to specified format"
      operationId: "getImg"
      parameters:
      - name: id
        in: path
        required: true
        example: "3fa85f64-5717-4562-b3fc-2c963f66afa6.jpg"
        schema:
          type: string
      responses:
        200:
          description: "OK"
          content:
            image:
              schema:
                type: string
                format: binary
                
  /image/compressed/{id}:
    get:
      summary: "Get original image, converted to specified format"
      operationId: "getCompressedImg"
      parameters:
      - name: id
        in: path
        required: true
        example: "3fa85f64-5717-4562-b3fc-2c963f66afa6.jpg"
        schema:
          type: string
      responses:
        200:
          description: "OK"
          content:
            image:
              schema:
                type: string
                format: binary